language: go
go_import_path: github.com/coreos/etcd

sudo: required

services: docker

go:
- tip

notifications:
  on_success: never
  on_failure: never

env:
  matrix:
  - TARGET=linux-amd64-build
  - TARGET=darwin-amd64-build
  - TARGET=linux-arm-build
  - TARGET=linux-arm64-build

matrix:
  fast_finish: true
  allow_failures:
  - go: tip
    env: TARGET=linux-amd64-fmt-unit-go-tip

before_install:
- if [[ $TRAVIS_GO_VERSION == 1.* ]]; then docker pull gcr.io/etcd-development/etcd-test:go${TRAVIS_GO_VERSION}; fi

install:
- go get -t -d ./...

script:
 - echo "TRAVIS_GO_VERSION=${TRAVIS_GO_VERSION}"
 - >
    case "${TARGET}" in
      linux-amd64-build)
        docker run --rm \
          --volume=`pwd`:/go/src/github.com/coreos/etcd gcr.io/etcd-development/etcd-test:go${TRAVIS_GO_VERSION} \
          /bin/bash -c "GOARCH=amd64 PASSES='build' ./test"
        ;;
      darwin-amd64-build)
        docker run --rm \
          --volume=`pwd`:/go/src/github.com/coreos/etcd gcr.io/etcd-development/etcd-test:go${TRAVIS_GO_VERSION} \
          /bin/bash -c "GO_BUILD_FLAGS='-v' GOOS=darwin GOARCH=amd64 ./build"
        ;;
      linux-arm-build)
        docker run --rm \
          --volume=`pwd`:/go/src/github.com/coreos/etcd gcr.io/etcd-development/etcd-test:go${TRAVIS_GO_VERSION} \
          /bin/bash -c "GO_BUILD_FLAGS='-v' GOARCH=arm ./build"
        ;;
      linux-arm64-build)
        docker run --rm \
          --volume=`pwd`:/go/src/github.com/coreos/etcd gcr.io/etcd-development/etcd-test:go${TRAVIS_GO_VERSION} \
          /bin/bash -c "GO_BUILD_FLAGS='-v' GOARCH=arm64 ./build"
        ;;
      linux-ppc64le-build)
        docker run --rm \
          --volume=`pwd`:/go/src/github.com/coreos/etcd gcr.io/etcd-development/etcd-test:go${TRAVIS_GO_VERSION} \
          /bin/bash -c "GO_BUILD_FLAGS='-v' GOARCH=ppc64le ./build"
        ;;
      linux-amd64-fmt-unit-go-tip)
        GOARCH=amd64 PASSES='fmt unit' ./test
        ;;
    esac
